#!/usr/bin/env bash

QUEUE="https://us-west-2.queue.amazonaws.com/535174415681/jg-queue-1"
MESSAGE=$(aws sqs receive-message --queue-url $QUEUE)
echo "Received message: "
echo $MESSAGE
RECEIPT=$(echo $MESSAGE | jq -r ".Messages[0].ReceiptHandle")
echo "Received receipt handle: $RECEIPT"
CMDRECEIVE="aws sqs delete-message --queue-url $QUEUE --receipt-handle $RECEIPT"
echo "$CMDRECEIVE"
$($CMDRECEIVE)
